from django.urls import path

from .views import account_approval, approvals, assessment_support, audit_log, content_center, content_toggle, crm_activity_create, crm_case_detail, crm_case_export, crm_case_update, crm_task_create, crm_task_toggle, crm_workspace, customer_contact_create, customer_detail, customer_workspace, dashboard, notification_feed, notification_list, notification_open, notification_status, payment_review, push_subscribe, request_detail, request_list, request_update, sms_send, staff_create, staff_edit, staff_list, ticket_status
from contracts.views import proposal_clauses, proposal_create, proposal_detail, proposal_list, proposal_publish

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("customers/", customer_workspace, name="customer_workspace"),
    path("customers/<int:customer_id>/", customer_detail, name="customer_detail"),
    path("customers/<int:customer_id>/contacts/new/", customer_contact_create, name="customer_contact_create"),
    path("crm/", crm_workspace, name="crm_workspace"),
    path("crm/cases/<int:case_id>/", crm_case_detail, name="crm_case_detail"),
    path("crm/cases/<int:case_id>/update/", crm_case_update, name="crm_case_update"),
    path("crm/cases/<int:case_id>/tasks/new/", crm_task_create, name="crm_task_create"),
    path("crm/tasks/<int:task_id>/toggle/", crm_task_toggle, name="crm_task_toggle"),
    path("crm/cases/<int:case_id>/activities/new/", crm_activity_create, name="crm_activity_create"),
    path("crm/cases/<int:case_id>/export/", crm_case_export, name="crm_case_export"),
    path("staff/", staff_list, name="staff_list"),
    path("staff/new/", staff_create, name="staff_create"),
    path("staff/<int:user_id>/", staff_edit, name="staff_edit"),
    path("notifications/", notification_list, name="notification_list"),
    path("notifications/feed/", notification_feed, name="notification_feed"),
    path("notifications/push/subscribe/", push_subscribe, name="push_subscribe"),
    path("notifications/<int:notification_id>/open/", notification_open, name="notification_open"),
    path("notifications/<int:notification_id>/<str:status>/", notification_status, name="notification_status"),
    path("sms/", sms_send, name="sms_send"),
    path("requests/", request_list, name="request_list"),
    path("requests/<str:kind>/<int:object_id>/", request_detail, name="request_detail"),
    path("requests/<str:kind>/<int:object_id>/update/", request_update, name="request_update"),
    path("contracts/", proposal_list, name="contract_list"),
    path("contracts/new/", proposal_create, name="contract_create"),
    path("contracts/<int:proposal_id>/", proposal_detail, name="contract_detail"),
    path("contracts/<int:proposal_id>/clauses/", proposal_clauses, name="contract_clauses"),
    path("contracts/<int:proposal_id>/publish/", proposal_publish, name="contract_publish"),
    path("approvals/", approvals, name="approvals"),
    path("approvals/accounts/<int:user_id>/<str:decision>/", account_approval, name="account_approval"),
    path("approvals/payments/<int:payment_id>/<str:decision>/", payment_review, name="payment_review"),
    path("assessment-support/", assessment_support, name="assessment_support"),
    path("assessment-support/tickets/<int:ticket_id>/status/", ticket_status, name="ticket_status"),
    path("content/", content_center, name="content_center"),
    path("content/<str:kind>/<int:object_id>/toggle/", content_toggle, name="content_toggle"),
    path("audit/", audit_log, name="audit_log"),
]
