from django.urls import path

from .views import account_approval, approvals, assessment_support, audit_log, content_center, content_toggle, crm_activity_create, crm_case_detail, crm_case_export, crm_case_update, crm_task_create, crm_task_toggle, crm_workspace, customer_account_open, customer_activity_create, customer_assessment_detail, customer_contact_create, customer_detail, customer_duplicates, customer_merge, customer_message_send, customer_reports, customer_segment_delete, customer_task_create, customer_workspace, dashboard, notification_assign, notification_claim, notification_feed, notification_list, notification_open, notification_payment_action, notification_snooze, notification_status, payment_review, push_subscribe, request_detail, request_export, request_list, request_update, sms_send, staff_create, staff_edit, staff_list, system_log, ticket_status
from contracts.views import contract_settings, proposal_clauses, proposal_create, proposal_delete, proposal_detail, proposal_edit, proposal_list, proposal_preview, proposal_publish, proposal_revoke
from .workspace_views import (
    workspace_access_create,
    workspace_access_revoke,
    workspace_contract_save,
    workspace_create,
    workspace_detail,
    workspace_general_terms,
    workspace_list,
    workspace_publish,
    workspace_questionnaire,
)

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("customers/", customer_workspace, name="customer_workspace"),
    path("customers/reports/", customer_reports, name="customer_reports"),
    path("customers/duplicates/", customer_duplicates, name="customer_duplicates"),
    path("customers/segments/<int:segment_id>/delete/", customer_segment_delete, name="customer_segment_delete"),
    path("customers/<int:source_id>/merge/", customer_merge, name="customer_merge"),
    path("customers/<int:customer_id>/", customer_detail, name="customer_detail"),
    path("customers/accounts/<int:user_id>/open/", customer_account_open, name="customer_account_open"),
    path("customers/<int:customer_id>/assessments/<int:user_id>/", customer_assessment_detail, name="customer_assessment_detail"),
    path("customers/<int:customer_id>/message/", customer_message_send, name="customer_message_send"),
    path("customers/<int:customer_id>/contacts/new/", customer_contact_create, name="customer_contact_create"),
    path("customers/<int:customer_id>/tasks/new/", customer_task_create, name="customer_task_create"),
    path("customers/<int:customer_id>/activities/new/", customer_activity_create, name="customer_activity_create"),
    path("crm/", crm_workspace, name="crm_workspace"),
    path("crm/cases/<int:case_id>/", crm_case_detail, name="crm_case_detail"),
    path("crm/cases/<int:case_id>/update/", crm_case_update, name="crm_case_update"),
    path("crm/cases/<int:case_id>/tasks/new/", crm_task_create, name="crm_task_create"),
    path("crm/tasks/<int:task_id>/toggle/", crm_task_toggle, name="crm_task_toggle"),
    path("crm/cases/<int:case_id>/activities/new/", crm_activity_create, name="crm_activity_create"),
    path("crm/cases/<int:case_id>/export/", crm_case_export, name="crm_case_export"),
    path("workspaces/", workspace_list, name="workspace_list"),
    path("workspaces/general-terms/", workspace_general_terms, name="workspace_general_terms"),
    path("workspaces/<int:case_id>/", workspace_detail, name="workspace_detail"),
    path("workspaces/<int:case_id>/create/", workspace_create, name="workspace_create"),
    path("workspaces/<int:case_id>/contract/", workspace_contract_save, name="workspace_contract_save"),
    path("workspaces/<int:case_id>/questionnaire/", workspace_questionnaire, name="workspace_questionnaire"),
    path("workspaces/<int:case_id>/access/", workspace_access_create, name="workspace_access_create"),
    path("workspaces/<int:case_id>/access/<int:grant_id>/revoke/", workspace_access_revoke, name="workspace_access_revoke"),
    path("workspaces/<int:case_id>/publish/", workspace_publish, name="workspace_publish"),
    path("staff/", staff_list, name="staff_list"),
    path("staff/new/", staff_create, name="staff_create"),
    path("staff/<int:user_id>/", staff_edit, name="staff_edit"),
    path("notifications/", notification_list, name="notification_list"),
    path("notifications/feed/", notification_feed, name="notification_feed"),
    path("notifications/push/subscribe/", push_subscribe, name="push_subscribe"),
    path("notifications/<int:notification_id>/open/", notification_open, name="notification_open"),
    path("notifications/<int:notification_id>/claim/", notification_claim, name="notification_claim"),
    path("notifications/<int:notification_id>/snooze/", notification_snooze, name="notification_snooze"),
    path("notifications/<int:notification_id>/assign/", notification_assign, name="notification_assign"),
    path("notifications/<int:notification_id>/payment/<str:decision>/", notification_payment_action, name="notification_payment_action"),
    path("notifications/<int:notification_id>/<str:status>/", notification_status, name="notification_status"),
    path("sms/", sms_send, name="sms_send"),
    path("requests/", request_list, name="request_list"),
    path("requests/<str:kind>/<int:object_id>/", request_detail, name="request_detail"),
    path("requests/<str:kind>/<int:object_id>/export/", request_export, name="request_export"),
    path("requests/<str:kind>/<int:object_id>/update/", request_update, name="request_update"),
    path("contracts/", proposal_list, name="contract_list"),
    path("contracts/settings/", contract_settings, name="contract_settings"),
    path("contracts/new/", proposal_create, name="contract_create"),
    path("contracts/<int:proposal_id>/", proposal_detail, name="contract_detail"),
    path("contracts/<int:proposal_id>/edit/", proposal_edit, name="contract_edit"),
    path("contracts/<int:proposal_id>/preview/", proposal_preview, name="contract_preview"),
    path("contracts/<int:proposal_id>/revoke/", proposal_revoke, name="contract_revoke"),
    path("contracts/<int:proposal_id>/delete/", proposal_delete, name="contract_delete"),
    path("contracts/<int:proposal_id>/clauses/", proposal_clauses, name="contract_clauses"),
    path("contracts/<int:proposal_id>/publish/", proposal_publish, name="contract_publish"),
    path("approvals/", approvals, name="approvals"),
    path("approvals/accounts/<int:user_id>/<str:decision>/", account_approval, name="account_approval"),
    path("approvals/payments/<int:payment_id>/<str:decision>/", payment_review, name="payment_review"),
    path("assessment-support/", assessment_support, name="assessment_support"),
    path("assessment-support/tickets/<int:ticket_id>/status/", ticket_status, name="ticket_status"),
    path("content/", content_center, name="content_center"),
    path("content/<str:kind>/<int:object_id>/toggle/", content_toggle, name="content_toggle"),
    path("audit/", audit_log, name="audit_log"),
    path("system-log/", system_log, name="system_log"),
]
