# Generated by Django 5.0.6 on 2025-08-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email_or_telegram', models.CharField(max_length=120)),
                ('request_type', models.CharField(choices=[('project', 'Project'), ('training', 'Training'), ('other', 'Other')], default='project', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
