# Generated by Django 5.0.6 on 2025-08-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='request_type',
            field=models.CharField(choices=[('project', 'Project Request'), ('training', 'Training Request'), ('other', 'Other')], default='project', max_length=20, verbose_name='Request Type'),
        ),
    ]
