# Generated by Django 4.2.30 on 2026-09-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_demotemplate_demoselection'),
        ('leads', '0004_lead_sales_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='demo_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='projects.demoselection'),
        ),
    ]
