# Generated by Django 4.2.30 on 2026-09-12 10:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import leads.models.form_draft


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0005_lead_demo_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('leads_contact', 'فرم تماس')], default='leads_contact', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=0, help_text='Zero-based step index; leads_contact has 3 steps (0–2).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('demo_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'باز'), ('submitting', 'در حال ثبت'), ('submitted', 'ثبت\u200cشده'), ('expired', 'منقضی\u200cشده')], db_index=True, default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=leads.models.form_draft.default_draft_expiry)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_drafts', to=settings.AUTH_USER_MODEL)),
                ('submitted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_form_drafts', to='leads.lead')),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['owner', 'status'], name='formdraft_owner_status_idx'), models.Index(fields=['status', 'expires_at'], name='formdraft_status_expiry_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='formdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'submitting'))), fields=('owner', 'form_type'), name='unique_active_form_draft_per_owner_and_form_type'),
        ),
    ]
