# Generated by Django 4.2.30 on 2026-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_formdraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdraft',
            name='revision',
            field=models.PositiveBigIntegerField(default=1, help_text='Optimistic-concurrency counter for the account-bound draft API. Starts at 1 on creation and increments by exactly 1 whenever fields/current_step/demo_snapshot/status actually change; an idempotent no-op save (identical content) never bumps it. leads.form_draft_service is the only code that may change it.'),
        ),
    ]
