# Generated by Django 4.2.30 on 2026-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_formdraft_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdraft',
            name='submission_token',
            field=models.CharField(blank=True, help_text="A non-secret, server-minted, single-use idempotency key for the final leads_contact submission this draft belongs to — never an access token. Set only by leads.form_draft_service.finalize_form_draft_to_lead, exactly once, when a submission first begins finalizing. Mirrors projects.DemoSelection.submission_token's own, already-proven shape and purpose.", max_length=64, null=True, unique=True),
        ),
    ]
