# Generated by Django 5.0.6 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(help_text='عنوان پروژه به فارسی', max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(help_text='Project title in English', max_length=200, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, help_text='توضیحات تکمیلی به فارسی', verbose_name='توضیح فارسی')),
                ('description_en', models.TextField(blank=True, help_text='Detailed description in English', verbose_name='توضیح انگلیسی')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, verbose_name='لینک پروژه')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
