# Generated by Django 4.2.30 on 2026-08-09 14:05

import blog.models.post
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_link_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), blog.models.post.validate_image_size], verbose_name='تصویر'),
        ),
    ]
