# Generated by Django 4.2.30 on 2026-09-09 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ecommerce', 'فروشگاه اینترنتی'), ('restaurant', 'رستوران و کافه'), ('portfolio', 'پورتفولیو'), ('corporate', 'وب\u200cسایت شرکتی'), ('clinic', 'کلینیک'), ('education', 'آموزش')], db_index=True, max_length=20)),
                ('title_fa', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('tagline_fa', models.CharField(max_length=220)),
                ('tagline_en', models.CharField(max_length=220)),
                ('fictional_brand_fa', models.CharField(max_length=120)),
                ('fictional_brand_en', models.CharField(max_length=120)),
                ('style_key', models.CharField(max_length=30)),
                ('default_features', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category', 'display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='DemoSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('selections', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='projects.demotemplate')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
