# Generated by Django 4.2.30 on 2026-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_seed_demo_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoselection',
            name='submission_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
