# Generated by Django 4.2.30 on 2026-10-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_demoselection_submission_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotemplate',
            name='category',
            field=models.CharField(choices=[('ecommerce', 'فروشگاه اینترنتی'), ('restaurant', 'رستوران و کافه'), ('portfolio', 'پورتفولیو'), ('corporate', 'وب\u200cسایت شرکتی'), ('clinic', 'کلینیک'), ('education', 'آموزش'), ('jewelry', 'طلافروشی و جواهرات')], db_index=True, max_length=20),
        ),
    ]
