# Generated by Django 4.2.30 on 2026-08-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_fa', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('description_fa', models.TextField()),
                ('description_en', models.TextField()),
                ('language_mode', models.CharField(choices=[('en', 'English only'), ('bilingual', 'Persian and English')], max_length=12)),
                ('question_count', models.PositiveSmallIntegerField(default=50)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('price_irr', models.PositiveIntegerField(default=500000)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_irr', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=12)),
                ('gateway', models.CharField(default='sandbox', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='assessments.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=30)),
                ('external_id', models.CharField(max_length=120, unique=True)),
                ('amount_irr', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('verified', 'Verified'), ('failed', 'Failed')], default='initiated', max_length=12)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assessments.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExamEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_remaining', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='assessments.exam')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement', to='assessments.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'exam', 'created_at'], name='order_user_exam_created'),
        ),
    ]
