# Generated by Django 4.2.30 on 2026-08-04 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_attempt_examsection_examversion_skill_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('incorrect_count', models.PositiveSmallIntegerField(default=0)),
                ('unanswered_count', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level_code', models.CharField(max_length=30)),
                ('level_title_fa', models.CharField(max_length=120)),
                ('level_title_en', models.CharField(max_length=120)),
                ('summary_fa', models.TextField()),
                ('summary_en', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='assessments.attempt')),
            ],
            options={
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='SkillResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('question_count', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='assessments.attemptresult')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessments.skill')),
            ],
            options={
                'ordering': ('skill__display_order', 'skill_id'),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='assessments.attemptresult')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='skillresult',
            constraint=models.UniqueConstraint(fields=('result', 'skill'), name='unique_result_skill'),
        ),
    ]
