# Generated by Django 4.2.30 on 2026-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_attemptresult_skillresult_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='choices_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='question_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='choice',
            name='explanation_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='explanation_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_response_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='exposure_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single choice'), ('code_analysis', 'Code analysis'), ('reading', 'Reading'), ('listening', 'Listening'), ('writing_objective', 'Writing objective')], db_index=True, default='single_choice', max_length=24),
        ),
        migrations.AddField(
            model_name='question',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='question',
            name='subskill',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='question',
            name='suggested_seconds',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
