# Generated by Django 4.2.30 on 2026-08-05 10:09

from django.db import migrations, models


def populate_difficulty_blueprints(apps, schema_editor):
    ExamSection = apps.get_model('assessments', 'ExamSection')
    for section in ExamSection.objects.all():
        distribution = {}
        for difficulty in section.questions.values_list('difficulty', flat=True):
            key = str(difficulty)
            distribution[key] = distribution.get(key, 0) + 1
        section.difficulty_distribution = distribution
        section.save(update_fields=['difficulty_distribution'])


def clear_difficulty_blueprints(apps, schema_editor):
    apps.get_model('assessments', 'ExamSection').objects.update(difficulty_distribution={})


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_attemptquestion_choices_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='selection_seed',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='examsection',
            name='difficulty_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='content_group',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(populate_difficulty_blueprints, clear_difficulty_blueprints),
    ]
