# Generated by Django 4.2.30 on 2026-08-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_attempt_selection_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='audio_play_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='max_plays',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
