# Generated by Django 4.2.30 on 2026-08-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_attemptquestion_selected_choice_snapshot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestion',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='answer_change_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='visit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrityevent',
            name='attempt_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_events', to='assessments.attemptquestion'),
        ),
        migrations.AddField(
            model_name='integrityevent',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
