# Generated by Django 4.2.30 on 2026-08-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_attemptquestion_active_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrityevent',
            name='event_type',
            field=models.CharField(choices=[('visibility_hidden', 'Page hidden'), ('visibility_returned', 'Returned to page'), ('tab_hidden', 'Tab hidden (legacy)'), ('window_blur', 'Window blur (legacy)'), ('copy', 'Copy'), ('paste', 'Paste'), ('other', 'Other')], max_length=20),
        ),
    ]
