# Generated by Django 4.2.30 on 2026-09-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_restore_legacy_tab_hidden_penalties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='price_irr',
            field=models.PositiveIntegerField(default=500000),
        ),
    ]
