# Generated by Django 4.2.30 on 2026-09-09 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0024_attemptquestion_last_save_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='examentitlement',
            name='revocation_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='examentitlement',
            name='revoked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='examentitlement',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_exam_entitlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
