# Generated by Django 4.2.30 on 2026-10-06 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0025_examentitlement_revocation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeAssessmentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='welcome_credit', to='assessments.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='welcome_assessment_credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
