# Generated by Django 4.2.30 on 2026-10-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_welcome_assessment_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='completion_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Manual submission'), ('timeout', 'Time expired'), ('copy_limit', 'Welcome copy limit')], max_length=10),
        ),
    ]
