# Generated by Django 4.2.30 on 2026-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='body_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='page',
            name='title_fa',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='PageTranslation',
        ),
    ]
