# Generated by Django 4.2.30 on 2026-08-11 10:52

import contracts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='پیشنهاد طراحی و توسعه سامانه', max_length=200)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_phone', models.CharField(max_length=16)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('project_title', models.CharField(max_length=200)),
                ('project_scope', models.TextField()),
                ('amount_irr', models.PositiveBigIntegerField()),
                ('payment_terms', models.TextField(default='۵۰٪ هنگام شروع و ۵۰٪ هنگام تحویل نهایی')),
                ('delivery_terms', models.CharField(help_text='مثال: ۸ هفته پس از دریافت پیش\u200cپرداخت و اطلاعات لازم', max_length=200)),
                ('client_details', models.TextField(blank=True)),
                ('token', models.CharField(default=contracts.models.contract_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال\u200cشده'), ('review', 'بازخورد مشتری'), ('accepted', 'پذیرفته\u200cشده'), ('expired', 'منقضی'), ('revoked', 'باطل\u200cشده')], db_index=True, default='draft', max_length=12)),
                ('current_version', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیشنهاد قرارداد',
                'verbose_name_plural': 'پیشنهادهای قرارداد',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_versions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='contracts.contractproposal')),
            ],
            options={
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='ContractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_clause_ids', models.JSONField(default=list)),
                ('rejected_clause_ids', models.JSONField(default=list)),
                ('rejection_notes', models.TextField(blank=True)),
                ('suggested_clause', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=240)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='contracts.contractversion')),
            ],
            options={
                'ordering': ('-reviewed_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contractproposal')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.UniqueConstraint(fields=('proposal', 'number'), name='unique_contract_version'),
        ),
    ]
