# Generated by Django 4.2.30 on 2026-08-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('code_hash', models.CharField(max_length=128)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otp_challenges', to='contracts.contractversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_phone', models.CharField(max_length=12)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=240)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance', to='contracts.contractversion')),
            ],
            options={
                'ordering': ('-accepted_at',),
            },
        ),
    ]
