# Generated by Django 4.2.30 on 2026-08-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractproposal_room_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRoomAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('general', 'شرایط عمومی پیمان'), ('private', 'شرایط خصوصی پیمان')], max_length=12)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=240)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_acknowledgements', to='contracts.contractversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contractroomacknowledgement',
            constraint=models.UniqueConstraint(fields=('version', 'document'), name='unique_contract_room_ack'),
        ),
    ]
