# Generated by Django 4.2.30 on 2026-08-11 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'ساخت همکار'), ('roles_updated', 'تغییر مسئولیت\u200cها')], max_length=24)),
                ('roles', models.JSONField(default=list)),
                ('staff_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_access_actions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_access_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سابقه دسترسی همکار',
                'verbose_name_plural': 'سوابق دسترسی همکاران',
                'ordering': ('-created_at',),
            },
        ),
    ]
