# Generated by Django 4.2.30 on 2026-08-11 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accounts', 'حساب\u200cها'), ('sales', 'فروش و سفارش'), ('payments', 'پرداخت'), ('support', 'پشتیبانی'), ('contracts', 'قرارداد')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('target_url', models.CharField(max_length=300)),
                ('role', models.CharField(blank=True, db_index=True, max_length=24)),
                ('source_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('unread', 'خوانده\u200cنشده'), ('read', 'خوانده\u200cشده'), ('resolved', 'مختومه')], db_index=True, default='unread', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_management_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعلان مدیریتی',
                'verbose_name_plural': 'اعلان\u200cهای مدیریتی',
                'ordering': ('-created_at',),
            },
        ),
    ]
