# Generated by Django 4.2.30 on 2026-08-11 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_portal', '0002_managementnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=12)),
                ('message', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق')], db_index=True, max_length=10)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('error_message', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_sms_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ارسال دستی پیامک',
                'verbose_name_plural': 'ارسال\u200cهای دستی پیامک',
                'ordering': ('-created_at',),
            },
        ),
    ]
