# Generated by Django 4.2.30 on 2026-08-15 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_portal', '0005_pushsubscription_notificationreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=management_portal.models.customer_case_code, editable=False, max_length=15, unique=True)),
                ('kind', models.CharField(choices=[('lead', 'همکاری'), ('crm', 'CRM'), ('clinic', 'کلینیک'), ('general', 'عمومی')], db_index=True, max_length=12)),
                ('customer_name', models.CharField(db_index=True, max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=24)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('stage', models.CharField(choices=[('new', 'جدید'), ('discovery', 'نیازسنجی'), ('qualified', 'واجد شرایط'), ('proposal', 'پیشنهاد/قرارداد'), ('won', 'موفق'), ('lost', 'بسته\u200cشده')], db_index=True, default='new', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری')], db_index=True, default='normal', max_length=10)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customer_cases', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rvion_customer_cases', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('done', 'انجام\u200cشده'), ('cancelled', 'لغوشده')], db_index=True, default='open', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'زیاد'), ('urgent', 'فوری')], db_index=True, default='normal', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customer_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='management_portal.customercase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'due_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initial', 'نیازسنجی اولیه'), ('specialist', 'نیازسنجی تخصصی'), ('contract', 'قرارداد'), ('payment', 'پرداخت'), ('export', 'خروجی'), ('attachment', 'پیوست')], db_index=True, max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='management_portal.customercase')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rvion_case_documents', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_case_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('system', 'سیستم'), ('note', 'یادداشت'), ('call', 'تماس'), ('message', 'پیام'), ('meeting', 'جلسه'), ('status', 'تغییر وضعیت'), ('document', 'سند'), ('task', 'وظیفه')], db_index=True, max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_case_activities', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='management_portal.customercase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='customercase',
            constraint=models.UniqueConstraint(condition=models.Q(('source_content_type__isnull', False), ('source_object_id__isnull', False)), fields=('source_content_type', 'source_object_id'), name='unique_customer_case_source'),
        ),
        migrations.AddConstraint(
            model_name='casedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('content_type__isnull', False), ('object_id__isnull', False)), fields=('case', 'content_type', 'object_id', 'kind'), name='unique_case_linked_document'),
        ),
    ]
