# Generated by Django 4.2 on 2026-08-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("management_portal", "0009_customer_customercontact_customercase_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementnotification",
            name="due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="managementnotification",
            name="owner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_management_notifications", to=settings.AUTH_USER_MODEL),
        ),
    ]
