# Generated by Django 4.2.30 on 2026-08-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_portal', '0010_managementnotification_owner_due_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('error', 'خطا'), ('warning', 'هشدار'), ('info', 'اطلاعات')], db_index=True, default='error', max_length=10)),
                ('category', models.CharField(choices=[('server', 'خطای سرور'), ('frontend', 'خطای مرورگر کاربر'), ('wizard', 'رفتار ویزارد'), ('other', 'سایر')], db_index=True, default='other', max_length=12)),
                ('message_fa', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد سیستمی',
                'verbose_name_plural': 'لاگ\u200cهای سیستم',
                'ordering': ('-created_at',),
            },
        ),
    ]
