# Generated by Django 4.2.30 on 2026-08-21 09:21

import hashlib
import json

from django.db import migrations, models
import django.db.models.deletion


def backfill_current_document_snapshots(apps, schema_editor):
    CaseDocument = apps.get_model("management_portal", "CaseDocument")
    CaseDocumentRevision = apps.get_model(
        "management_portal", "CaseDocumentRevision"
    )
    batch = []
    for document in CaseDocument.objects.all().iterator(chunk_size=500):
        snapshot = document.snapshot if isinstance(document.snapshot, dict) else {}
        checksum = document.checksum or hashlib.sha256(
            json.dumps(
                snapshot,
                sort_keys=True,
                ensure_ascii=False,
            ).encode("utf-8")
        ).hexdigest()
        batch.append(
            CaseDocumentRevision(
                document_id=document.pk,
                title=document.title,
                snapshot=snapshot,
                checksum=checksum,
            )
        )
        if len(batch) >= 500:
            CaseDocumentRevision.objects.bulk_create(batch, batch_size=500)
            batch = []
    if batch:
        CaseDocumentRevision.objects.bulk_create(batch, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('management_portal', '0011_systemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('snapshot', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='management_portal.casedocument')),
            ],
            options={
                'verbose_name': 'نسخه سند پرونده',
                'verbose_name_plural': 'نسخه\u200cهای اسناد پرونده',
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.RunPython(
            backfill_current_document_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='casedocumentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'checksum'), name='unique_case_document_revision_checksum'),
        ),
    ]
