# Generated by Django 4.2.30 on 2026-08-27 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_portal', '0012_case_document_revisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('title_fa', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120)),
                ('body_fa', models.TextField(max_length=1000)),
                ('body_en', models.TextField(max_length=1000)),
                ('audience', models.CharField(choices=[('registered', 'عضو بدون سفارش'), ('unpaid', 'سفارش پرداخت\u200cنشده'), ('payment_review', 'پرداخت منتظر بررسی'), ('ready', 'پرداخت\u200cشده و شروع\u200cنشده'), ('completed', 'نتیجه آماده'), ('manual', 'دستی')], db_index=True, default='manual', max_length=24)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('registered', 'عضو بدون سفارش'), ('unpaid', 'سفارش پرداخت\u200cنشده'), ('payment_review', 'پرداخت منتظر بررسی'), ('ready', 'پرداخت\u200cشده و شروع\u200cنشده'), ('completed', 'نتیجه آماده'), ('manual', 'دستی')], db_index=True, max_length=24)),
                ('message', models.TextField(max_length=1000)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='smsdispatch',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='management_portal.smscampaign'),
        ),
    ]
