# Generated by Django 4.2.30 on 2026-08-27 07:26

from django.db import migrations


TEMPLATES = (
    ("registered-followup", "یادآوری ثبت سفارش", "Order reminder", "registered", "حساب شما در آرویون فعال است. برای شروع آزمون وارد rvionai.com شوید و سفارش خود را ثبت کنید.", "Your Rvion account is active. Visit rvionai.com to choose and order an assessment."),
    ("unpaid-followup", "یادآوری تکمیل پرداخت", "Payment reminder", "unpaid", "سفارش شما در آرویون ثبت شده اما پرداخت کامل نشده است. برای ادامه وارد rvionai.com شوید.", "Your Rvion order is saved, but payment is incomplete. Visit rvionai.com to continue."),
    ("payment-review", "دریافت رسید پرداخت", "Payment receipt received", "payment_review", "رسید پرداخت شما دریافت شد و در حال بررسی است. نتیجه از طریق حساب آرویون اطلاع‌رسانی می‌شود.", "We received your payment receipt and it is under review. The result will appear in your Rvion account."),
    ("ready-reminder", "یادآوری شروع آزمون", "Assessment start reminder", "ready", "دسترسی آزمون شما فعال است. برای شروع وارد حساب خود در rvionai.com شوید.", "Your assessment access is active. Sign in at rvionai.com to begin."),
    ("result-followup", "اطلاع آماده‌شدن نتیجه", "Result ready", "completed", "نتیجه آزمون شما آماده است. برای مشاهده گزارش وارد حساب خود در rvionai.com شوید.", "Your assessment result is ready. Sign in at rvionai.com to view the report."),
)


def seed_templates(apps, schema_editor):
    template_model = apps.get_model("management_portal", "SMSMessageTemplate")
    for order, values in enumerate(TEMPLATES, start=1):
        key, title_fa, title_en, audience, body_fa, body_en = values
        template_model.objects.get_or_create(key=key, defaults={
            "title_fa": title_fa, "title_en": title_en, "audience": audience,
            "body_fa": body_fa, "body_en": body_en, "display_order": order,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('management_portal', '0013_smsmessagetemplate_smscampaign_smsdispatch_campaign'),
    ]

    operations = [migrations.RunPython(seed_templates, migrations.RunPython.noop)]
