# Generated by Django 4.2.30 on 2026-08-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_portal', '0014_seed_sms_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict)),
                ('is_shared', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_customer_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'هویت و عضویت'), ('sales', 'فروش و نیازسنجی'), ('order', 'سفارش'), ('payment', 'پرداخت'), ('assessment', 'آزمون'), ('contract', 'قرارداد'), ('support', 'پشتیبانی'), ('communication', 'ارتباط'), ('task', 'وظیفه'), ('system', 'سیستم')], db_index=True, max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('title_fa', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('dedupe_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_customer_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_events', to='management_portal.customercase')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='management_portal.customer')),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='savedcustomersegment',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_saved_segment_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='customerevent',
            index=models.Index(fields=['customer', 'event_type', 'occurred_at'], name='cust_event_timeline_idx'),
        ),
    ]
