# Generated by Django 4.2.30 on 2026-09-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_portal', '0016_backfill_customer_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementnotification',
            name='priority',
            field=models.CharField(choices=[('critical', 'بحرانی'), ('high', 'زیاد'), ('normal', 'معمولی'), ('low', 'کم')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='managementnotification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
