# Generated by Django 4.2.30 on 2026-10-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_portal', '0019_notification_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscampaign',
            name='submission_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
