import{initial,ROUTES,chooseRoute,chooseStyle,toggleFeature,back,finalize}from'./journey-model.mjs';
import{phase,clamp}from'./film-model.mjs';
const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg';let state=initial(),busy=false,raf=0,manual=false,lastClip=null,finish=null;
const os=matchMedia('(prefers-reduced-motion:reduce)');
const names={cart:'سبد خرید',delivery:'پیگیری ارسال',booking:'رزرو میز',menu:'منوی دیجیتال'};
const titles={welcome:['یک ایده، چند مسیر.','اول یک سکانس کوتاه؛ بعد انتخاب با توست.'],business:['برای چه کسب‌وکاری بسازیم؟','یک مسیر انتخاب کن؛ سکانس بعدی مختص همان موضوع است.'],style:['چه حسی داشته باشد؟','چیدمان و فرم سایت هم تغییر می‌کند، نه فقط رنگ آن.'],features:['چه کاری برای مشتری انجام دهد؟','هر انتخاب یک سکانس کوتاه دارد. امکانات اجباری نیستند.'],summary:['این طرح، از انتخاب‌های تو ساخته شد.','می‌توانی برگردی و هر بخش را تغییر بدهی.']};
const icons={shop:'<path d="M7 17h30l-3-10H10Z M10 17v23h24V17 M18 40V27h8v13"/>',restaurant:'<path d="M12 5v14m-5-14v9q0 7 10 7V5M12 21v22M32 5q-9 12 0 18v20M32 5v18"/>',modern:'<rect x="5" y="6" width="34" height="34" rx="2"/><path d="M5 17h34M17 17v23"/>',warm:'<rect x="5" y="6" width="34" height="34" rx="12"/><circle cx="22" cy="23" r="9"/>',feature:'<path d="M5 22h34M22 5v34"/><circle cx="22" cy="22" r="18"/>'};
function icon(key){return `<svg viewBox="0 0 44 44" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">${icons[key]||icons.feature}</svg>`;}
function button(key,title,detail,selected,handler){const b=document.createElement('button');b.type='button';b.className='choice';b.disabled=busy;b.setAttribute('aria-pressed',String(selected));const image=document.createElement('span');image.className='icon';image.innerHTML=icon(key);const text=document.createElement('span');const strong=document.createElement('strong');strong.textContent=title;const small=document.createElement('small');small.textContent=detail;text.append(strong,small);const check=document.createElement('span');check.className='check';check.textContent=selected?'✓':'‹';check.setAttribute('aria-hidden','true');b.append(image,text,check);b.addEventListener('click',handler);$('choices').append(b);}
function ui(focus=false){
 const [title,hint]=titles[state.step];$('prompt').textContent=title;$('hint').textContent=hint;$('choices').replaceChildren();$('summary').replaceChildren();$('summary').hidden=state.step!=='summary';
 document.body.classList.toggle('busy',busy);$('play-state').textContent=busy?'سکانس در حال اجرا':'منتظر انتخاب تو';$('status').textContent=busy?'می‌توانی سکانس را رد کنی.':state.step==='summary'?'پیش‌نمایش آماده است؛ چیزی ارسال نشده.':'انتخاب بعدی آماده است.';
 for(const step of ['business','style','features','summary']){const el=$('step-'+step);if(step===state.step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');}
 $('skip').disabled=!busy;$('replay').disabled=!lastClip||busy;$('back').disabled=['welcome','business'].includes(state.step);$('next').hidden=!['features','summary'].includes(state.step);$('next').disabled=busy;$('next').textContent=state.step==='summary'?'شروع از اول':'دیدن نتیجه';
 if(state.step==='business'){button('shop','فروشگاه','ساخت محصول، مجموعه و سبد خرید',state.route==='shop',()=>{state=chooseRoute(state,'shop');play('business');});button('restaurant','رستوران','چیدمان غذا، منو و رزرو میز',state.route==='restaurant',()=>{state=chooseRoute(state,'restaurant');play('business');});}
 if(state.step==='style'){button('modern','مدرن و ساختاریافته','فرم‌های دقیق، چیدمان تفکیک‌شده و رنگ عمیق',state.style==='modern',()=>{state=chooseStyle(state,'modern');play('style');});button('warm','گرم و روایت‌محور','فرم‌های نرم، تصویر بزرگ و رنگ طبیعی',state.style==='warm',()=>{state=chooseStyle(state,'warm');play('style');});}
 if(state.step==='features')for(const key of ROUTES[state.route].features)button('feature',names[key],state.features.includes(key)?'فعال است؛ برای حذف لمس کن.':'برای دیدن سکانس این امکان لمس کن.',state.features.includes(key),()=>{state=toggleFeature(state,key);play(key);});
 if(state.step==='summary'){const dl=document.createElement('dl');for(const[label,value]of[['موضوع',ROUTES[state.route].label],['سبک',state.style==='warm'?'گرم و روایت‌محور':'مدرن و ساختاریافته'],['امکانات',state.features.map(v=>names[v]).join('، ')||'بدون امکانات اضافه']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dl.append(dt,dd);}const note=document.createElement('p');note.textContent='در نسخه اصلی، همین انتخاب‌ها به سفارش متصل خواهند شد. این دمو فقط مسیر را نشان می‌دهد.';$('summary').append(dl,note);}
 if(focus){$('prompt').focus({preventScroll:true});if(matchMedia('(max-width:800px)').matches)$('prompt').scrollIntoView({block:'nearest',behavior:'instant'});}
}
function set(el,attrs){for(const[k,v]of Object.entries(attrs))el.setAttribute(k,String(v));}
const chair='<path d="M627 376Q598 302 632 281Q677 258 731 292L748 386Z" fill="#bd7f54"/><path d="M615 371Q674 347 757 385L746 431Q683 450 625 430Z" fill="#ddb88e"/><path d="M635 425L619 486M731 425L748 486" stroke="#6d4933" stroke-width="10" stroke-linecap="round"/>';
const dish='<ellipse cx="692" cy="459" rx="119" ry="20" fill="#000" opacity=".12"/><circle cx="692" cy="365" r="112" fill="#f7eddb" stroke="#c8b293" stroke-width="3"/><circle cx="692" cy="365" r="88" fill="#dfcaa6"/><path d="M629 328Q682 310 740 341L735 391Q673 424 635 379Z" fill="#b86638"/><path d="M630 330L737 381M649 316L737 358M628 351L716 401" stroke="#6d3927" stroke-width="4"/><g fill="#526b36"><ellipse cx="641" cy="405" rx="17" ry="8" transform="rotate(25 641 405)"/><ellipse cx="754" cy="310" rx="18" ry="9" transform="rotate(-32 754 310)"/><ellipse cx="623" cy="314" rx="14" ry="6"/></g><circle cx="741" cy="413" r="17" fill="#e8ba47"/>';
function art(){
 const route=ROUTES[state.route||'shop'],warm=state.style==='warm',restaurant=state.route==='restaurant';$('brand-name').textContent=route.brand;$('mock-title').textContent=restaurant?'A table. A story.':'Made for living.';$('mock-subtitle').textContent=restaurant?'Seasonal food. Shared moments.':'Objects with a story of their own.';
 $('paper').setAttribute('fill',warm?'#f6efe1':'#e7eced');$('paper').setAttribute('rx',warm?'13':'2');$('mock-title').setAttribute('fill',warm?'#35432f':'#263b55');$('mock-title').setAttribute('font-size',warm?'43':'36');
 $('visual').innerHTML=`<rect x="557" y="242" width="280" height="260" rx="${warm?35:3}" fill="${warm?'url(#surface)':'#b4c7d1'}"/>${restaurant?dish:chair}`;
 $('products').innerHTML=restaurant?'<rect x="165" y="353" width="330" height="136" rx="12" fill="#e7d8c1"/><text x="188" y="386" fill="#594835" font-size="16">Seasonal menu</text><path d="M188 411H444M188 433H402M188 455H427" stroke="#ad9275" stroke-width="3"/>':'<rect x="160" y="357" width="180" height="132" rx="10" fill="#e4d7c2"/><rect x="356" y="357" width="160" height="132" rx="10" fill="#e4d7c2"/><path d="M199 411h97l-13-31h-68Z M248 411v58" fill="#c2a782" stroke="#71634f" stroke-width="4"/><path d="M413 466v-52q-8-27 20-27q28 0 20 27v52Z" fill="#b8bfa4"/>';
 $('feature-scene').innerHTML=featuresMarkup();$('scene-name').textContent=state.step==='welcome'?'از ایده تا تجربه':`${route.label} · ${warm?'گرم':'مدرن'}`;$('scene-title').textContent=state.step==='welcome'?'ایده به نقشه سایت تبدیل می‌شود':`پیش‌نمایش ${route.label} با سبک ${warm?'گرم':'مدرن'}`;
}
function featuresMarkup(){if(!state.features.length)return'<path d="M166 535H420M166 551H343" stroke="#939985" stroke-width="3"/>';return state.features.map((key,i)=>{const x=165+i*335;const detail={cart:'Basket · 1 item',delivery:'Delivery · tracked',booking:'Friday · 2 guests',menu:'Menu · seasonal'}[key];return`<g><rect x="${x}" y="518" width="310" height="56" rx="14" fill="${state.style==='warm'?'#42513c':'#263b55'}"/><text x="${x+155}" y="552" fill="#fff4e3" font-size="16" text-anchor="middle">${detail}</text></g>`;}).join('');}
function draw(t,kind){const k=phase(t,0,1),welcome=kind==='welcome',modern=state.style==='modern';set($('spark'),{opacity:welcome?1-phase(t,.05,.7):0,transform:`rotate(${t*100} 500 350)`});set($('site'),{opacity:welcome?phase(t,.15,.8):1,transform:`translate(500 350) rotate(${(1-k)*(welcome?-12:5)}) scale(${welcome?.3+k*.7: .94+k*.06}) translate(-500 -350)`});
 set($('visual'),{opacity:welcome?phase(t,.55,1):phase(t,.1,.85),transform:`translate(${(modern?-390:0)+(1-k)*(state.route==='restaurant'?140:-100)} ${kind==='style'?(1-k)*-25:0})`});set($('products'),{opacity:welcome?phase(t,.65,1):phase(t,.25,.95),transform:`translate(${modern?335:0} ${(1-k)*60})`});set($('headline-art'),{opacity:welcome?phase(t,.6,1):1,transform:`translate(${modern?350:0} 0)`});set($('feature-scene'),{opacity:phase(t,.35,.95),transform:`translate(0 ${(1-k)*-35})`});set($('result'),{opacity:state.step==='summary'?k:0});$('clip-progress').style.transform=`scaleX(${t})`;$('scene').dataset.clip=kind;$('scene').dataset.progress=t.toFixed(3);}
function cancel(){cancelAnimationFrame(raf);raf=0;finish=null;busy=false;}
function play(kind,done=null){cancel();lastClip=kind;busy=true;art();ui();if(matchMedia('(max-width:800px)').matches)window.scrollTo({top:0,behavior:'instant'});let elapsed=0,last=0;const duration=kind==='welcome'?2700:kind==='business'?1700:1200;
 const complete=()=>{cancelAnimationFrame(raf);raf=0;draw(1,kind);busy=false;finish=null;if(done)done();ui(true);};finish=complete;
 if(os.matches||manual){complete();return;}
 function tick(now){if(!last)last=now;const dt=now-last;last=now;if(!document.hidden)elapsed+=Math.min(dt,50);draw(clamp(elapsed/duration),kind);if(elapsed>=duration)complete();else raf=requestAnimationFrame(tick);}draw(0,kind);raf=requestAnimationFrame(tick);
}
function welcome(){state=initial();play('welcome',()=>{state={...state,step:'business'};});}
$('skip').addEventListener('click',()=>finish?.());$('replay').addEventListener('click',()=>play(lastClip));
$('back').addEventListener('click',()=>{cancel();state=back(state);lastClip=state.step==='business'?'welcome':state.step==='style'?'business':'style';art();draw(1,lastClip);ui(true);});
$('next').addEventListener('click',()=>{if(state.step==='summary')welcome();else{state=finalize(state);play('result');}});
function reduction(){if(os.matches||manual)finish?.();$('reduce').setAttribute('aria-pressed',String(os.matches||manual));$('reduce').textContent=os.matches?'مطابق تنظیم دستگاه':manual?'فعال کردن حرکت':'کاهش حرکت';$('reduce').disabled=os.matches;}
$('reduce').disabled=false;$('reduce').addEventListener('click',()=>{manual=!manual;reduction();});os.addEventListener('change',reduction);reduction();welcome();
