# Generated by Django 5.0.6 on 2025-08-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات (فارسی)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default=' ', max_length=160, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_fa',
            field=models.CharField(default=' ', max_length=160, verbose_name='عنوان (فارسی)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است؟'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)'),
        ),
        migrations.DeleteModel(
            name='ServiceTranslation',
        ),
    ]
