# Generated by Django 5.0.6 on 2025-08-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_description_en_service_description_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='توضیحات انگلیسی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='توضیحات فارسی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=160, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_fa',
            field=models.CharField(max_length=160, verbose_name='عنوان فارسی'),
        ),
    ]
