# Generated by Django 5.0.6 on 2025-08-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full Body (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_fa',
            field=models.TextField(blank=True, null=True, verbose_name='متن کامل (فارسی)'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=170, null=True, verbose_name='Slug (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=170, null=True, verbose_name='نامک (فارسی)'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_en',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Summary (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_fa',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='خلاصه (فارسی)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='عنوان (فارسی)'),
        ),
        migrations.DeleteModel(
            name='PostTranslation',
        ),
    ]
