# Generated by Django 5.0.6 on 2025-08-31 15:10

import blog.models.post
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body_en_post_body_fa_post_slug_en_post_slug_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), blog.models.post.validate_image_size]),
        ),
    ]
