# Generated by Django 4.2.30 on 2026-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=170, null=True, unique=True, verbose_name='Slug (English)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=170, null=True, unique=True, verbose_name='نامک (فارسی)'),
        ),
    ]
