# Generated by Django 4.2.30 on 2026-08-09 14:14

import crm_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=crm_orders.models.crm_tracking_code, editable=False, max_length=14, unique=True)),
                ('organization_name', models.CharField(max_length=180)),
                ('industry', models.CharField(max_length=120)),
                ('organization_size', models.CharField(choices=[('1_10', '۱ تا ۱۰'), ('11_50', '۱۱ تا ۵۰'), ('51_200', '۵۱ تا ۲۰۰'), ('over_200', 'بیش از ۲۰۰')], max_length=12)),
                ('website', models.URLField(blank=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=120)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('primary_goals', models.JSONField(default=list)),
                ('departments', models.JSONField(default=list)),
                ('crm_user_count', models.CharField(choices=[('under_10', 'کمتر از ۱۰'), ('10_30', '۱۰ تا ۳۰'), ('31_100', '۳۱ تا ۱۰۰'), ('over_100', 'بیش از ۱۰۰')], max_length=12)),
                ('current_process', models.TextField()),
                ('main_pain_points', models.TextField()),
                ('success_metrics', models.TextField()),
                ('required_capabilities', models.JSONField(default=list)),
                ('critical_workflows', models.TextField()),
                ('reports_needed', models.TextField()),
                ('permission_requirements', models.TextField()),
                ('current_tools', models.TextField(blank=True)),
                ('required_integrations', models.TextField(blank=True)),
                ('migration_sources', models.TextField(blank=True)),
                ('approximate_record_count', models.PositiveIntegerField(blank=True, null=True)),
                ('hosting_preference', models.CharField(choices=[('cloud', 'ابری'), ('on_premise', 'داخل سازمان'), ('unsure', 'نیازمند بررسی')], max_length=20)),
                ('security_requirements', models.TextField(blank=True)),
                ('budget_range', models.CharField(choices=[('unsure', 'نیازمند برآورد'), ('under_150', 'کمتر از ۱۵۰ میلیون تومان'), ('150_500', '۱۵۰ تا ۵۰۰ میلیون تومان'), ('500_1500', '۵۰۰ میلیون تا ۱.۵ میلیارد تومان'), ('over_1500', 'بیش از ۱.۵ میلیارد تومان')], max_length=16)),
                ('expected_timeline', models.CharField(choices=[('urgent', 'کمتر از ۲ ماه'), ('2_4', '۲ تا ۴ ماه'), ('4_8', '۴ تا ۸ ماه'), ('flexible', 'منعطف')], max_length=12)),
                ('decision_process', models.TextField()),
                ('additional_notes', models.TextField(blank=True)),
                ('privacy_accepted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'جدید'), ('discovery', 'جلسه تحلیل'), ('qualified', 'واجد شرایط'), ('proposal', 'پیشنهاد ارسال شد'), ('won', 'قرارداد'), ('lost', 'بسته\u200cشده')], db_index=True, default='new', max_length=12)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
