# Generated by Django 4.2.30 on 2026-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmorder',
            name='ai_use_cases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='assignment_model',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='audit_requirement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='correspondence_features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='current_data_sources',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='customer_data_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='customer_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='delivery_strategy',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='devices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='integration_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='lead_sources',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='migration_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='mobile_requirement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='notification_channels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='reminder_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='reporting_priorities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='requested_services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crmorder',
            name='system_roles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='crmorder',
            name='budget_range',
            field=models.CharField(choices=[('under_100', 'کمتر از ۱۰۰ میلیون تومان'), ('100_250', '۱۰۰ تا ۲۵۰ میلیون تومان'), ('250_500', '۲۵۰ تا ۵۰۰ میلیون تومان'), ('over_500', 'بیش از ۵۰۰ میلیون تومان'), ('estimate', 'ابتدا نیازمند برآورد'), ('private', 'تمایل ندارم اعلام کنم')], max_length=16),
        ),
        migrations.AlterField(
            model_name='crmorder',
            name='crm_user_count',
            field=models.CharField(choices=[('1_5', '۱ تا ۵'), ('6_15', '۶ تا ۱۵'), ('16_30', '۱۶ تا ۳۰'), ('over_30', 'بیش از ۳۰'), ('unsure', 'هنوز مشخص نیست')], max_length=12),
        ),
        migrations.AlterField(
            model_name='crmorder',
            name='expected_timeline',
            field=models.CharField(choices=[('under_1', 'کمتر از یک ماه'), ('1_2', '۱ تا ۲ ماه'), ('2_4', '۲ تا ۴ ماه'), ('over_4', 'بیشتر از ۴ ماه'), ('unsure', 'زمان مشخصی نداریم')], max_length=12),
        ),
        migrations.AlterField(
            model_name='crmorder',
            name='hosting_preference',
            field=models.CharField(choices=[('cloud', 'آنلاین از هر مکان'), ('on_premise', 'فقط شبکه داخلی'), ('hybrid', 'ترکیبی با دسترسی امن'), ('unsure', 'نیازمند بررسی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='crmorder',
            name='organization_size',
            field=models.CharField(choices=[('under_10', 'کمتر از ۱۰'), ('10_30', '۱۰ تا ۳۰'), ('31_100', '۳۱ تا ۱۰۰'), ('over_100', 'بیش از ۱۰۰')], max_length=12),
        ),
    ]
