# Generated by Django 4.2.30 on 2026-08-15 09:20

import crm_orders.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_orders', '0002_crmorder_ai_use_cases_crmorder_assignment_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmSpecialistDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=crm_orders.models.specialist_token, editable=False, max_length=64, unique=True)),
                ('answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'تکمیل\u200cشده'), ('reviewed', 'بررسی\u200cشده')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_discovery', to='crm_orders.crmorder')),
            ],
            options={
                'verbose_name': 'نیازسنجی تخصصی CRM',
                'verbose_name_plural': 'نیازسنجی\u200cهای تخصصی CRM',
            },
        ),
    ]
