# Generated by Django 4.2.30 on 2026-08-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(max_length=64, unique=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('path', models.CharField(blank=True, max_length=160)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-last_seen',),
            },
        ),
        migrations.CreateModel(
            name='TrafficDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.PositiveBigIntegerField(default=0)),
                ('unique_visitors', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='DailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitor_hash', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='daily_visitor_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyvisitor',
            constraint=models.UniqueConstraint(fields=('date', 'visitor_hash'), name='unique_daily_visitor'),
        ),
    ]
