server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    client_max_body_size 5m;

    location /static/ { alias /srv/arvion/staticfiles/; access_log off; expires 7d; }
    location /media/ { alias /srv/arvion/media/; access_log off; expires 1d; }
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;
        proxy_connect_timeout 5s;
        proxy_read_timeout 65s;
    }
}
