server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name rvionai.com www.rvionai.com 188.121.101.173;
    client_max_body_size 5m;
    server_tokens off;
    gzip on;
    gzip_static on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml application/json application/javascript application/manifest+json application/xml image/svg+xml;

    location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; default_type text/plain; }
    location /static/ { alias /srv/arvion/staticfiles/; access_log off; expires 30d; add_header Cache-Control "public" always; }
    location /media/ { alias /srv/arvion/media/; access_log off; expires 1d; }
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;
        proxy_connect_timeout 5s;
        proxy_read_timeout 65s;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name rvionai.com www.rvionai.com;
    client_max_body_size 5m;
    server_tokens off;
    gzip on;
    gzip_static on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml application/json application/javascript application/manifest+json application/xml image/svg+xml;

    ssl_certificate /etc/nginx/ssl/rvionai.crt;
    ssl_certificate_key /etc/nginx/ssl/rvionai.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:RVIONSSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    location ^~ /.well-known/acme-challenge/ { root /var/www/certbot; default_type text/plain; }
    location /static/ { alias /srv/arvion/staticfiles/; access_log off; expires 30d; add_header Cache-Control "public" always; }
    location /media/ { alias /srv/arvion/media/; access_log off; expires 1d; }
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8000;
        proxy_connect_timeout 5s;
        proxy_read_timeout 65s;
    }
}
